from .attention import (
    CausalDotProductAttentionKernel,
    DotProductAttentionKernel,
    GroupedQueryAttentionKernel,
    MaskedDotProductAttentionKernel,
)
from .level1 import (
    AddKernel,
    ArgmaxKernel,
    ArgminKernel,
    CrossEntropyLossKernel,
    CumprodKernel,
    CumsumKernel,
    ELUKernel,
    FancyFusedKernel,
    GELUKernel,
    HardSigmoidKernel,
    HardtanhKernel,
    HingeLossKernel,
    KLDivBatchMeanKernel,
    L1NormKernel,
    L2NormKernel,
    LeakyReLUKernel,
    LogSoftmaxKernel,
    MaskedCumsumKernel,
    MeanSquaredErrorKernel,
    MinDimKernel,
    MSELossKernel,
    ReduceSumKernel,
    ReLUKernel,
    ReLUReductionKernel,
    ReverseCumsumKernel,
    SELUKernel,
    SigmoidKernel,
    SmoothL1LossKernel,
    SoftmaxKernel,
    SoftplusKernel,
    SoftsignKernel,
    SumDimKernel,
    SwishKernel,
    TanhKernel,
    TripletMarginLossKernel,
)
from .level2 import (
    AvgPool1dKernel,
    AvgPool2dKernel,
    AvgPool3dKernel,
    Conv2dKernel,
    MatrixAdditionKernel,
    MatrixMultiplicationKernel,
    MatrixScalarAdditionKernel,
    MatrixVectorMultiplicationKernel,
    MaxPool1dKernel,
    MaxPool1dWithIndicesKernel,
    MaxPool2dKernel,
    MaxPool2dWithIndicesKernel,
    MaxPool3dKernel,
    MaxPool3dWithIndicesKernel,
    RMSNormKernel,
)
from .level3 import (
    Conv2dMishMishKernel,
    Conv2dReLUBiasKernel,
    Conv3dReLULeakyReLUGELUSigmoidBiasKernel,
    ConvTranspose2dAddClampScaleClampDivideKernel,
    ConvTranspose2dSubTanhKernel,
    LinearDivideSumScaleKernel,
    LinearMulLeakyReLUKernel,
    LinearReLUDivideKernel,
    LinearScaleBatchNormKernel,
    LinearSigmoidSumKernel,
    LinearSwishDivideClampTanhClampKernel,
)
from .specials import (
    DifferenceOfSquaresKernel,
    InverseSquareRootKernel,
    MonteCarloPiKernel,
    TrigonometricIdentityKernel,
)


def available_kernels() -> dict[str, type]:
    return {operator.__name__: operator for operator in kernel_list}


def resolve_kernel(name: str) -> type:
    kernels = available_kernels()
    if name not in kernels:
        available = ", ".join(sorted(kernels))
        raise ValueError(f"Unknown kernel {name!r}. Available kernels: {available}")
    return kernels[name]


kernel_list = [
    CausalDotProductAttentionKernel,
    DotProductAttentionKernel,
    GroupedQueryAttentionKernel,
    MaskedDotProductAttentionKernel,
    DifferenceOfSquaresKernel,
    InverseSquareRootKernel,
    MonteCarloPiKernel,
    TrigonometricIdentityKernel,
    AvgPool1dKernel,
    AvgPool2dKernel,
    AvgPool3dKernel,
    Conv2dMishMishKernel,
    Conv2dKernel,
    Conv2dReLUBiasKernel,
    Conv3dReLULeakyReLUGELUSigmoidBiasKernel,
    ConvTranspose2dAddClampScaleClampDivideKernel,
    ConvTranspose2dSubTanhKernel,
    AddKernel,
    ArgmaxKernel,
    ArgminKernel,
    CrossEntropyLossKernel,
    CumprodKernel,
    CumsumKernel,
    ELUKernel,
    FancyFusedKernel,
    GELUKernel,
    HardSigmoidKernel,
    HardtanhKernel,
    HingeLossKernel,
    KLDivBatchMeanKernel,
    L1NormKernel,
    L2NormKernel,
    LeakyReLUKernel,
    LogSoftmaxKernel,
    MaskedCumsumKernel,
    MatrixAdditionKernel,
    MatrixMultiplicationKernel,
    MatrixScalarAdditionKernel,
    MatrixVectorMultiplicationKernel,
    LinearDivideSumScaleKernel,
    LinearMulLeakyReLUKernel,
    LinearReLUDivideKernel,
    LinearScaleBatchNormKernel,
    LinearSigmoidSumKernel,
    LinearSwishDivideClampTanhClampKernel,
    MaxPool1dKernel,
    MaxPool1dWithIndicesKernel,
    MaxPool2dKernel,
    MaxPool2dWithIndicesKernel,
    MaxPool3dKernel,
    MaxPool3dWithIndicesKernel,
    MeanSquaredErrorKernel,
    MinDimKernel,
    MSELossKernel,
    ReduceSumKernel,
    RMSNormKernel,
    ReLUKernel,
    ReLUReductionKernel,
    ReverseCumsumKernel,
    SELUKernel,
    SigmoidKernel,
    SoftmaxKernel,
    SoftplusKernel,
    SoftsignKernel,
    SmoothL1LossKernel,
    SumDimKernel,
    SwishKernel,
    TanhKernel,
    TripletMarginLossKernel,
]
