
import torch
import triton
import triton.language as tl

from triton_ptx.helpers import get_ptx_constexpr, jit_fixed_parameters
from triton_ptx.kernels.base import TritonPTXKernel

_ptx_kernel = {
    "ptx": r"""//
// Generated by LLVM NVPTX Back-End
//

.version 8.7
.target sm_89
.address_size 64

	// .globl	kernel                  // -- Begin function kernel
                                        // @kernel
.visible .entry kernel(
	.param .u64 .ptr .global .align 1 kernel_param_0,
	.param .u64 .ptr .global .align 1 kernel_param_1,
	.param .u64 .ptr .global .align 1 kernel_param_2,
	.param .u32 kernel_param_3,
	.param .u64 .ptr .global .align 1 kernel_param_4,
	.param .u64 .ptr .global .align 1 kernel_param_5
)
.reqntid 128
{
	.reg .pred 	%p<9>;
	.reg .b32 	%r<39>;
	.reg .b64 	%rd<30>;
	.loc	1 17 0                          // add.py:17:0
$L__func_begin0:
	.loc	1 17 0                          // add.py:17:0

// %bb.0:
	ld.param.b64 	%rd25, [kernel_param_0];
	ld.param.b64 	%rd26, [kernel_param_1];
$L__tmp0:
	.loc	1 24 24                         // add.py:24:24
	mov.u32 	%r25, %ctaid.x;
	.loc	1 25 24                         // add.py:25:24
	shl.b32 	%r26, %r25, 10;
	ld.param.b64 	%rd27, [kernel_param_2];
	ld.param.b32 	%r27, [kernel_param_3];
	.loc	1 26 41                         // add.py:26:41
	mov.u32 	%r28, %tid.x;
	and.b32 	%r29, %r28, 127;
	.loc	1 26 28                         // add.py:26:28
	or.b32 	%r30, %r26, %r29;
	or.b32 	%r31, %r30, 128;
	or.b32 	%r32, %r30, 256;
	or.b32 	%r33, %r30, 384;
	or.b32 	%r34, %r30, 512;
	or.b32 	%r35, %r30, 640;
	or.b32 	%r36, %r30, 768;
	or.b32 	%r37, %r28, %r26;
	or.b32 	%r38, %r37, 896;
	.loc	1 27 21                         // add.py:27:21
	setp.lt.s32 	%p1, %r30, %r27;
	setp.lt.s32 	%p2, %r31, %r27;
	setp.lt.s32 	%p3, %r32, %r27;
	setp.lt.s32 	%p4, %r33, %r27;
	setp.lt.s32 	%p5, %r34, %r27;
	setp.lt.s32 	%p6, %r35, %r27;
	setp.lt.s32 	%p7, %r36, %r27;
	setp.lt.s32 	%p8, %r38, %r27;
	.loc	1 29 24                         // add.py:29:24
	mul.wide.s32 	%rd28, %r30, 4;
	add.s64 	%rd1, %rd25, %rd28;
	add.s64 	%rd2, %rd1, 512;
	add.s64 	%rd3, %rd1, 1024;
	add.s64 	%rd4, %rd1, 1536;
	add.s64 	%rd5, %rd1, 2048;
	add.s64 	%rd6, %rd1, 2560;
	add.s64 	%rd7, %rd1, 3072;
	mul.wide.s32 	%rd29, %r38, 4;
	add.s64 	%rd8, %rd25, %rd29;
	.loc	1 29 16                         // add.py:29:16
	// begin inline asm
	mov.u32 %r1, 0x0;
	@%p1 ld.global.b32 { %r1 }, [ %rd1 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r2, 0x0;
	@%p2 ld.global.b32 { %r2 }, [ %rd2 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r3, 0x0;
	@%p3 ld.global.b32 { %r3 }, [ %rd3 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r4, 0x0;
	@%p4 ld.global.b32 { %r4 }, [ %rd4 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r5, 0x0;
	@%p5 ld.global.b32 { %r5 }, [ %rd5 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r6, 0x0;
	@%p6 ld.global.b32 { %r6 }, [ %rd6 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r7, 0x0;
	@%p7 ld.global.b32 { %r7 }, [ %rd7 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r8, 0x0;
	@%p8 ld.global.b32 { %r8 }, [ %rd8 + 0 ];
	// end inline asm
	.loc	1 30 24                         // add.py:30:24
	add.s64 	%rd9, %rd26, %rd28;
	add.s64 	%rd10, %rd9, 512;
	add.s64 	%rd11, %rd9, 1024;
	add.s64 	%rd12, %rd9, 1536;
	add.s64 	%rd13, %rd9, 2048;
	add.s64 	%rd14, %rd9, 2560;
	add.s64 	%rd15, %rd9, 3072;
	add.s64 	%rd16, %rd26, %rd29;
	.loc	1 30 16                         // add.py:30:16
	// begin inline asm
	mov.u32 %r9, 0x0;
	@%p1 ld.global.b32 { %r9 }, [ %rd9 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r10, 0x0;
	@%p2 ld.global.b32 { %r10 }, [ %rd10 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r11, 0x0;
	@%p3 ld.global.b32 { %r11 }, [ %rd11 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r12, 0x0;
	@%p4 ld.global.b32 { %r12 }, [ %rd12 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r13, 0x0;
	@%p5 ld.global.b32 { %r13 }, [ %rd13 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r14, 0x0;
	@%p6 ld.global.b32 { %r14 }, [ %rd14 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r15, 0x0;
	@%p7 ld.global.b32 { %r15 }, [ %rd15 + 0 ];
	// end inline asm
	// begin inline asm
	mov.u32 %r16, 0x0;
	@%p8 ld.global.b32 { %r16 }, [ %rd16 + 0 ];
	// end inline asm
	.loc	1 31 17                         // add.py:31:17
	add.f32 	%r17, %r1, %r9;
	add.f32 	%r18, %r2, %r10;
	add.f32 	%r19, %r3, %r11;
	add.f32 	%r20, %r4, %r12;
	add.f32 	%r21, %r5, %r13;
	add.f32 	%r22, %r6, %r14;
	add.f32 	%r23, %r7, %r15;
	add.f32 	%r24, %r8, %r16;
	.loc	1 32 26                         // add.py:32:26
	add.s64 	%rd17, %rd27, %rd28;
	add.s64 	%rd18, %rd17, 512;
	add.s64 	%rd19, %rd17, 1024;
	add.s64 	%rd20, %rd17, 1536;
	add.s64 	%rd21, %rd17, 2048;
	add.s64 	%rd22, %rd17, 2560;
	add.s64 	%rd23, %rd17, 3072;
	add.s64 	%rd24, %rd27, %rd29;
	.loc	1 32 35                         // add.py:32:35
	// begin inline asm
	@%p1 st.global.b32 [ %rd17 + 0 ], { %r17 };
	// end inline asm
	// begin inline asm
	@%p2 st.global.b32 [ %rd18 + 0 ], { %r18 };
	// end inline asm
	// begin inline asm
	@%p3 st.global.b32 [ %rd19 + 0 ], { %r19 };
	// end inline asm
	// begin inline asm
	@%p4 st.global.b32 [ %rd20 + 0 ], { %r20 };
	// end inline asm
	// begin inline asm
	@%p5 st.global.b32 [ %rd21 + 0 ], { %r21 };
	// end inline asm
	// begin inline asm
	@%p6 st.global.b32 [ %rd22 + 0 ], { %r22 };
	// end inline asm
	// begin inline asm
	@%p7 st.global.b32 [ %rd23 + 0 ], { %r23 };
	// end inline asm
	// begin inline asm
	@%p8 st.global.b32 [ %rd24 + 0 ], { %r24 };
	// end inline asm
	.loc	1 32 4                          // add.py:32:4
	ret;
$L__tmp1:
$L__func_end0:
                                        // -- End function
}
	.file	1 "/workspace/triton_ptx/kernels/add.py"
	.section	.debug_abbrev
	{
.b8 1                                   // Abbreviation Code
.b8 17                                  // DW_TAG_compile_unit
.b8 0                                   // DW_CHILDREN_no
.b8 37                                  // DW_AT_producer
.b8 8                                   // DW_FORM_string
.b8 19                                  // DW_AT_language
.b8 5                                   // DW_FORM_data2
.b8 3                                   // DW_AT_name
.b8 8                                   // DW_FORM_string
.b8 16                                  // DW_AT_stmt_list
.b8 6                                   // DW_FORM_data4
.b8 27                                  // DW_AT_comp_dir
.b8 8                                   // DW_FORM_string
.b8 0                                   // EOM(1)
.b8 0                                   // EOM(2)
.b8 0                                   // EOM(3)
	}
	.section	.debug_info
	{
.b32 58                                 // Length of Unit
.b8 2                                   // DWARF version number
.b8 0
.b32 .debug_abbrev                      // Offset Into Abbrev. Section
.b8 8                                   // Address Size (in bytes)
.b8 1                                   // Abbrev [1] 0xb:0x33 DW_TAG_compile_unit
.b8 116                                 // DW_AT_producer
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2                                   // DW_AT_language
.b8 0
.b8 97                                  // DW_AT_name
.b8 100
.b8 100
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line                        // DW_AT_stmt_list
.b8 47                                  // DW_AT_comp_dir
.b8 119
.b8 111
.b8 114
.b8 107
.b8 115
.b8 112
.b8 97
.b8 99
.b8 101
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 95
.b8 112
.b8 116
.b8 120
.b8 47
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 115
.b8 0
	}
	.section	.debug_macinfo	{	}""",
    "KERNEL_BLOCK_SIZE": 1024,
}




class AddKernel(TritonPTXKernel):
    def __init__(self, *, block_size=1024, ptx=_ptx_kernel):
        self.block_size = block_size
        self.init_compiled_kernels(ptx=ptx, jit=jit_fixed_parameters)

    @staticmethod
    def kernel(
        x_ptr,
        y_ptr,
        output_ptr,
        n_elements,
        KERNEL_BLOCK_SIZE: tl.constexpr,
    ):
        pid = tl.program_id(axis=0)
        block_start = pid * KERNEL_BLOCK_SIZE
        offsets = block_start + tl.arange(0, KERNEL_BLOCK_SIZE)
        mask = offsets < n_elements

        x = tl.load(x_ptr + offsets, mask=mask)
        y = tl.load(y_ptr + offsets, mask=mask)
        output = x + y
        tl.store(output_ptr + offsets, output, mask=mask)

    def get_random_input(self, size=10_000_000):
        x = torch.randn(size, device="cuda")
        y = torch.randn(size, device="cuda")
        return x, y

    def forward_triton(self, inputs, ptx=False):
        x, y = inputs
        n_elements = x.numel()
        output = torch.empty_like(x)
        grid = lambda meta: (triton.cdiv(n_elements, meta["KERNEL_BLOCK_SIZE"]),)

        if not ptx:
            kernel = self.compiled_kernel[grid](
                x, y, output, n_elements, KERNEL_BLOCK_SIZE=self.block_size,
            )
        else:
            kernel = self.require_compiled_ptx()[grid](
                x,
                y,
                output,
                n_elements,
                KERNEL_BLOCK_SIZE=(
                    get_ptx_constexpr(self.ptx, "KERNEL_BLOCK_SIZE")
                    or self.block_size
                ),
            )
        return output, kernel

    def forward_torch(self, inputs):
        x, y = inputs
        return x + y
